config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :skip => [:registrations]
  get 'home/home'
  get 'home/contact'
  root to: 'home#home'
  resources :tickets, param: :reference_key
  match 'tickets/send_notification' => 'tickets#send_notification', :as =>'send_notification', via: [:post]

end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  before_validation :fill_fields
  after_create :send_created_ticket_email, :start_history
  after_update :send_updated_ticket_email, :add_history_record
  validates :reference_key,
            format: { with: /(([A-Z]{3}-([A-F]|[0-9]){2})-){2}[A-Z]{3}/i},
            uniqueness: { case_sensitive: false },
            presence: true
  validates :customer_name,
            format: { with: /\A([A-Z][a-z ,.'`-]{2,60})\z/i, message: 'Only allows letters' },
            length: { in: 1..60, message: 'Length must be between 1 and 60' },
            presence: true
  validates :customer_email,
            format: { with: /\A([\w-]+(?:\.[\w-]+)*)@((?:[\w-]+\.)*\w[\w-]{0,66})\.([a-z]{2,6}(?:\.[a-z]{2})?)\z/i, message: 'Not email format' },
            presence: true
  validates :description,
            format: { with: /\A([A-Z][a-z0-9 ,.'`-]{2,250})\z/i, message: 'Only allows letters and numbers' },
            length: { in: 1..250, message: 'Length must be between 1 and 250' },
            presence: true
  validates :department_id, :subject_id, :status_id, presence: true
  belongs_to :department
  belongs_to :subject
  belongs_to :status
  belongs_to :owner, class_name: "User"
  has_many :ticket_histories

  def self.find_by_filter (filter)
    case filter
      when "open"
        Ticket.where(owner_id: nil).all
      when "on_hold"
        Ticket.where(["status_id = ? or status_id = ?",
                      "#{Status.find_by_name('Waiting for Customer').id}",
                      "#{Status.find_by_name('On Hold').id}"]).all
      when "closed"
        Ticket.where(["status_id = ? or status_id = ?",
                      "#{Status.find_by_name('Cancelled').id}",
                      "#{Status.find_by_name('Completed').id}"]).all
    end
  end

  def update_attributes_by_customer(ticket_params)
    reset_status
    self.update_attributes(ticket_params)
  end

  def to_param
    reference_key
  end
  private

    def start_history
      TicketHistory.create(ticket_id: self.id, description: 'Ticket has been created.')
    end

    def add_history_record
      TicketHistory.create(ticket_id: self.id, description: update_message(self))
    end

    def reset_status
      self.status_id = Status.find_by_name('Waiting for Staff Response').id
    end

    def send_created_ticket_email
      CustomerMailer.created_ticked_email(self).deliver_now
    end

    def send_updated_ticket_email
      message = update_message(self)
      CustomerMailer.updated_ticked_email(self, message).deliver_now
    end

    def update_message(ticket)
      message = ""
      ticket.changed.each do |field|
        case field
          when "customer_name"
            message += "Customer name was changed to #{ticket.customer_name}. "
          when "customer_email"
            message += "Customer email was changed to #{ticket.customer_email}. "
          when "department_id"
            message += "Department was changed to #{ticket.department.name}. "
          when "subject_id"
            message += "Subject was changed to #{ticket.subject.name}. "
          when "owner_id"
            message += "Owner was changed to #{ticket.owner.full_name}. "
          when "status_id"
            message += "Status was changed to #{ticket.status.name}. "
          when "description"
            message += "Description was changed."
        end
      end
      message
    end

    def fill_fields
      if self.new_record?
        self.reference_key = generate_reference_key
        reset_status
      end
    end

    def generate_reference_key
      key = ''
      loop do
        key = /((\w{3}-((A|B|C|D|E|F)|\d){2})-){2}\w{3}/.gen.upcase
        break unless Ticket.where(reference_key: key).first
      end
      key
    end

end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:show, :edit, :update, :destroy, :send_notification]
  before_action :authenticate_user!, only: [:index, :send_notification]

  def index
    if params[:filter].presence
      if params[:filter] == 'my'
        @tickets = Ticket.where("owner_id = ?", "#{current_user.id}")
        @tab = 'my'
      else
        @tickets = Ticket.find_by_filter(params[:filter])
        @tab = params[:filter]
      end
    else
      @tickets = Ticket.find_by_filter('open')
      @tab = 'open'
    end
    # binding.pry
  end

  def show
  end

  def new
    @ticket = Ticket.new
  end

  def edit
    @notification = ""
  end

  def create
    @ticket = Ticket.new(ticket_params)
    if @ticket.save
      redirect_to @ticket
    else
      render :new
    end
  end

  def update
    if signed_in?
      if @ticket.update_attributes(staf_ticket_params)
        redirect_to @ticket
      else
        render action: "edit"
      end
    else
      if @ticket.update_attributes_by_customer(ticket_params)
        redirect_to @ticket
      else
        render action: "edit"
      end
    end
  end

  def send_notification
    message = params[:notification]
    CustomerMailer.notification_email(@ticket, message).deliver_now
    @ticket
  end

  # def destroy
  #   @ticket.destroy
  #   redirect_to tickets_url
  # end

  private

  def set_ticket
    @ticket = Ticket.find_by(reference_key: params[:reference_key])
  end

  def ticket_params
    params.require(:ticket).permit(:customer_name,
                                   :customer_email,
                                   :department_id,
                                   :subject_id,
                                   :description)
  end

  def staf_ticket_params
    params.require(:ticket).permit(:owner_id,
                                   :status_id)
  end
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/tickets/_errors.html.erb
<% if @ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
        <% @ticket.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/tickets/_form.html.erb
<%= form_for(@ticket) do |f| %>
    <%= render 'errors' %>
  <div>
    <%= f.label "Your name:" %><br>
    <%= f.text_field :customer_name %>
  </div>
  <div>
    <%= f.label "Your e-mail:" %><br>
    <%= f.email_field :customer_email %>
  </div>
  <div>
    <%= f.label "Connected department:" %><br>
    <%= collection_select(:ticket, :department_id, Department.all, :id, :name) %>
  </div>
  <div>
    <%= f.label "Subject:" %><br>
    <%= collection_select(:ticket, :subject_id, Subject.all, :id, :name) %>
  </div>
  <div>
    <%= f.label "Description:" %><br>
    <%= f.text_area :description, :size => '80x10' %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tickets/_notification.html.erb
<h2>Send notification to customer</h2>

<%= form_for @notification, :url => url_for(:controller => 'tickets', :action => 'send_notification', :reference_key=>@ticket.reference_key) do |f| %>
    <div>
      <%= f.text_area :notification, :size => '80x10' %>
    </div>
    <div class="actions">
      <%= f.submit "Send" %>
    </div>
<% end %>

app/views/tickets/_staff_form.html.erb
<%= form_for(@ticket) do |f| %>
    <%= render 'errors' %>
  <div>
    <%= f.label "Owner:" %><br>
    <%= collection_select(:ticket, :owner_id, User.all, :id, :full_name) %>
  </div>
  <div>
    <%= f.label "Status:" %><br>
    <%= collection_select(:ticket, :status_id, Status.all, :id, :name) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tickets/_ticket_history.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-offset-2 col-md-offset-2 col-xs-offset-3 col-sm-offset-2 col-lg-8 col-md-2 col-sm-2 col-xs-6">
      <h3>History</h3>

      <table class = "table" width = "100%">
        <tr>
          <th>Date</th>
          <th>Descroption</th>
        </tr>

        <% @ticket.ticket_histories.each do |history| %>
          <tr>
            <td class = "center"><%= history.created_at.to_formatted_s(:long) %></td>
            <td class = "center"><%= history.description %></td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/tickets/_ticket_info.html.erb
<p>
  <strong>Customer:</strong>
  <%= @ticket.customer_name %>
</p>

<p>
  <strong>Customer e-mail:</strong>
  <%= @ticket.customer_email %>
</p>

<p>
  <strong>Customer:</strong>
  <%= @ticket.customer_name %>
</p>

<p>
  <strong>Department:</strong>
  <%= @ticket.department.name %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @ticket.subject.name %>
</p>

<p>
  <strong>Status:</strong>
  <%= @ticket.status.name %>
</p>

<p>
  <strong>Owner:</strong>
  <%= @ticket.owner.full_name if @ticket.owner.presence %>
</p>

<p>
  <strong>Description:</strong>
  <%= @ticket.description %>
</p>

app/views/tickets/edit.html.erb
<h2>Editing Ticket</h2>

<% if signed_in? %>
    <%= render 'ticket_info' %>
    <%= render 'staff_form' %>
    <%= render 'notification' %>
<% else %>
    <%= render 'form' %>
<% end %>

app/views/tickets/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-offset-2 col-md-offset-2 col-xs-offset-3 col-sm-offset-2 col-lg-8 col-md-2 col-sm-2 col-xs-6">
    <h1>Listing Tickets</h1>

    <ul class="nav nav-tabs nav-justified">
      <li <%= "class = active" if @tab == 'open' %>><%= link_to "Open tickets", tickets_path(filter: 'open'), remote: false %></li>
      <li <%= "class = active" if @tab == 'on_hold' %>><%= link_to "On hold tickets", tickets_path(filter: 'on_hold'), remote: false %></li>
      <li <%= "class = active" if @tab == 'closed' %>><%= link_to "Closed tickets", tickets_path(filter: 'closed'), remote: false %></li>
      <li <%= "class = active" if @tab == 'my' %>><%= link_to "My tickets", tickets_path(filter: 'my'), remote: false %></li>
    </ul>

    <table class = "table-striped" width = "100%">
      <tr>
        <th class = "center">Customer</th>
        <th class = "center">Description</th>
        <th class = "center">Status</th>
        <th class = "center"></th>
        <th class = "center"></th>
      </tr>

      <% @tickets.each do |ticket| %>
        <tr>
          <td><%= ticket.customer_name %></td>
          <td><%= ticket.description %></td>
          <td><%= ticket.status.name %></td>
          <td><%= link_to 'Show', ticket_path(ticket) %></td>
          <td><%= link_to 'Edit', edit_ticket_path(ticket) %></td>

        </tr>
      <% end %>
    </table>
    </div>
  </div>
</div>

app/views/tickets/new.html.erb
<h2>New Ticket</h2>

<%= render 'form' %>

app/views/tickets/send_notification.html.erb
<h2>Notification has been sent.</h2>
<%= link_to "Back", edit_ticket_path(@ticket) %>

app/views/tickets/show.html.erb
<h2>Ticket</h2>

<%= render "ticket_info" %>

<%= link_to 'Edit', edit_ticket_path(@ticket) %>

<%= render 'ticket_history' %>