config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :skip => [:registrations]
  get 'home/home'
  get 'home/contact'
  root to: 'home#home'
  resources :tickets, param: :reference_key
  match 'tickets/send_notification' => 'tickets#send_notification', :as =>'send_notification', via: [:post]

end

app/views/layouts/_header.html.erb
<header class="navbar navbar-default navbar-fixed-top navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to "Company", root_path, id: "logo" %>
    </div>
    <div class="nav navbar-nav pull-right">
      <ul class="nav navbar-nav">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", "#" %></li>
          <% if signed_in? %>
            <li><%= link_to "Tickets", tickets_path %></li>
            <li><%= link_to "Sign out", destroy_user_session_path, method: "delete" %></li>
          <% else %>
            <li><%= link_to "Contact us", home_contact_path %></li>
            <li><%= link_to "Sign in", new_user_session_path %></li>
          <% end %>
      </ul>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SupportIssueTracker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
    <div class="center">
        <%= yield %>
    </div>
</body>
</html>